#! /bin/bash

#Script Name: Loops
#Purpose:to kill one or more of the running procesees
#Example usage: To kill one or more of the unnecesary/harmufl tasks
#Expected output: to kill procesees
#Variable: yes, no
#Function: 

task (){
  
    read -a option -p "would you like to see active processes? "
    echo $(ps -aux)
    echo ""
    echo "Please do not delete something essential like kernel drivers"
   
   while [ true ]
   do
        echo "when finished teminating tasks just live blank and press return"
        read -a PID -p "Select PID of the process you would you like to kill? "
        kill ${PID}
        
        if [[ "${PID}" == "" ]]; then
        break
        fi
    done
echo "Have a good day"

}

task
